language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - cp .env.example .env
  - cp .test.env.example djangoRestApi/settings/.test.env

install:
  - make install

before_script:
  - docker-compose -f docker-compose-dev.yml up -d

script:
  - make test
  - make flake8

after_script:
  - docker-compose -f docker-compose-dev.yml down