language: python

python:
  - '3.8'

env:
  global:
    #HOST
    secure: UXQSuynf1/cxxZxlANdrj/yu4nwA+sEdQlJED8VhirJ2XzWSXoG+L0hHQrcjYfYSktEIHPSkZNwrkbbsT8o95gxJOyd1p8uxIFDEsnjYP/tjW/rsYP24/VGK+MI9ICyHGlQO/EBK29Z2qstNZnIcBC2z3Kb4urKIi9vu+3R0Hw+5JlR7KnoRX1bJd7drrO9liCs15rf5GFIhtkJ85BkrjjmX5T2V5eN5mtCqssY9jFghiVMNvNcWXkqcCYLLD1wqR2nhA8WMlBnE32F54cf1MHCxDjkV2HJmedYBGG5DffLoY8SM9xxO9hfe/CcxLKxCc8XnRHhujXevoK8kv71mSvFvOEGHbtkWqm6l4v43wPg72MODPmWP647h77ACg4UnqZzLNMpQWHOzyFVhkURaegKYasd25OpriOF84ZEBoo2vucmSiaXQA7krdyUs3ht+4AcXpLXm9x0/AYeo8z5rP59focSY5Vf6ahfanXGZIImJkpRXlb0SVxnLZYyKSHPyVMTdlKV4RZd/uEmxswzEs065sKf6UZKO9XhlIQ1LaEs2q06fh3zEClphSwLzuuj+zBUxi5DA2VV459i3Qy3Lzv4HovgVFaoUbuxE2VtriL5f6CS94ClD7Nsm92KKj9cVpMk4+TcfKDmEma1Hh1eBqv7xXFlgt+5X+B91pFiAX9Y=

services:
  - docker

addons:
  ssh_known_hosts: $MY_SSH_KNOWN_HOST

before_install:
  - cp .env.example .env
  - cp .test.env.example djangoRestApi/settings/.test.env

install:
  - make install

before_script:
  - docker-compose -f docker-compose-dev.yml up -d

script:
  - make wait-for-db && make test
  - make flake8

after_script:
  - docker-compose -f docker-compose-dev.yml down

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f4eabd9cea96_key -iv $encrypted_f4eabd9cea96_iv -in deploy_key.pem.enc -out /tmp/deploy_key.pem -d
  - eval "$(ssh-agent -s)"            # start the ssh agent
  - chmod 600 /tmp/deploy_key.pem     # this key should have push access
  - ssh-add /tmp/deploy_key.pem       # Add the private key to SSH

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: main

after_deploy:

after_success:
