version: '3'

services:

  my-django-backend-app:
    restart: always
    env_file:
      - .env
    #image: ${DOCKER_HUB_ID}/my-django-backend-app:production
    image: my-django-backend-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - static_data:/vol/web
    depends_on:
      - postgres


  postgres:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
  static_data:
  pgdata: