# Generated by Django 3.1.2 on 2020-10-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
