# Generated by Django 3.1.2 on 2020-10-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userId',
            new_name='user_id',
        ),
    ]
