version: '3'

services:

  postgres:
    image: postgres:latest
    volumes:
      - "django_rest_api-pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=django_rest_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  django_rest_api-pgdata:

# docker-compose -f env-setup/docker-compose-dev.yml -p django_rest_api up -d